# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

#before_all do
#    isCi = ENV["IS_CI"]
#    if isCi.nil?
#    	ENV["FLUTTER_ROOT"] = ".fvm/flutter_sdk"
#    end
#  end

import 'StaticAnalyze'
